[install]
# Use exact versions for dependencies
exact = true

[env]
# Load environment variables from .env files
DOT_ENV = true

[http]
# Optimize HTTP requests
keepalive = true
https-only = true

[runtime]
# Enable fetch streaming for better performance
streaming = true

[websocket]
# Enable WebSocket compression
compression = true
# Increase max payload size
max_payload_size = "16mb"
# Set ping interval for connection health checks
ping_interval = 30000 