name: Automated Tasks

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  push:
    branches: 
      - main
      - develop
    paths:
      - "supabase/migrations/**"
      - "src/**"
  pull_request:
    branches: 
      - main
      - develop
    paths:
      - "supabase/migrations/**"
      - "src/**"

jobs:
  update-types-and-sitemap:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      SITE_URL: ${{ secrets.SITE_URL }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          bun install
          pip install requests beautifulsoup4

      - name: Update Database Types
        run: |
          bun run update:types
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Generate Sitemap
        run: bun run generate:sitemap
        env:
          SITE_URL: ${{ secrets.SITE_URL }}

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Check if there are any changes to commit
          if [[ -n "$(git status --porcelain)" ]]; then
            git add database.types.ts public/sitemap.xml
            git commit -m "chore: update types and sitemap [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi 