name: Expire Pending Transactions

on:
  schedule:
    # Runs every 2 hours
    - cron: '0 */2 * * *'
  workflow_dispatch:
    # Allows manual triggering
    inputs:
      expiry_hours:
        description: 'Hours after which to expire pending transactions'
        required: false
        default: '2'
        type: string

jobs:
  expire:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret availability
        run: |
          if [ -n "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" ]; then
            echo "SUPABASE_SERVICE_ROLE_KEY is available"
          else
            echo "SUPABASE_SERVICE_ROLE_KEY is NOT available"
          fi
      
      - name: Invoke expiration function
        run: |
          curl -X POST "https://mdswvokxrnfggrujsfjd.supabase.co/functions/v1/expire-pending-transactions" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"expiry_hours": ${{ inputs.expiry_hours || 2 }}}' 