name: Generate Monthly Platform Invoices

on:
  schedule:
    # Runs at 00:01 UTC on the 25th of every month
    - cron: '1 0 25 * *'
  workflow_dispatch:
    # Allows manual triggering

jobs:
  generate-invoices:
    runs-on: ubuntu-latest
    steps:
      - name: Try RPC endpoint
        id: rpc-attempt
        continue-on-error: true
        run: |
          response=$(curl -s -X POST "https://mdswvokxrnfggrujsfjd.supabase.co/rest/v1/rpc/generate_monthly_statements_for_all_merchants" \
          -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json")
          
          echo "Response from RPC endpoint: $response"
          
          if [[ $response != *"error"* ]] && [[ $response != *"message"* ]]; then
            echo "Success using RPC endpoint!"
            exit 0
          fi
          
          # If we get here, RPC endpoint failed
          echo "RPC endpoint failed, trying alternative methods..."
          exit 1
          
      - name: Try Edge Function
        id: edge-function-attempt
        if: steps.rpc-attempt.outcome == 'failure'
        continue-on-error: true
        run: |
          response=$(curl -s -X POST "https://mdswvokxrnfggrujsfjd.supabase.co/functions/v1/generate-monthly-invoices" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json")
          
          echo "Response from Edge Function: $response"
          
          if [[ $response != *"error"* ]] && [[ $response != *"message"* ]]; then
            echo "Success using Edge Function!"
            exit 0
          fi
          
          # Edge function failed too
          echo "Edge function failed, trying database function..."
          exit 1
          
      - name: Execute SQL directly
        if: steps.rpc-attempt.outcome == 'failure' && steps.edge-function-attempt.outcome == 'failure'
        run: |
          response=$(curl -s -X POST "https://mdswvokxrnfggrujsfjd.supabase.co/rest/v1/sql" \
          -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"query": "SELECT generate_monthly_statements_for_all_merchants();"}')
          
          echo "Response from direct SQL execution: $response" 