name: Generate Monthly Statements

on:
  schedule:
    # Runs at 01:00 UTC on the 25th of each month
    - cron: '0 1 25 * *'
  workflow_dispatch:
    # Allows manual triggering

jobs:
  generate-statements:
    runs-on: ubuntu-latest
    steps:
      - name: Generate monthly statements
        run: |
          curl -X POST "https://mdswvokxrnfggrujsfjd.supabase.co/functions/v1/generate-monthly-statements" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json" 